### ISSUE TITLE
How to use it in Symfony 5?

### ISSUE THREAD

**Issue by fd6130** [pixelfederation/doctrine-resettable-em-bundle#21]
Hi, I'm not sure how to use this in Symfony 5 with swoole-bundle.. any guideline for novice like me? Thanks.

**Comment by Rastusik** [comment]
Hi, as stated in the README, you just have to activate the bundle

```
// config/bundles.php
return [
    //...
    \PixelFederation\DoctrineResettableEmBundle\PixelFederationDoctrineResettableEmBundle::class => ['all' => true]
    //...
];
```

that is basically it ... one important thing is that you have to inject the EntityManagerInterface into your services, not the concrete EntityManager class, because this bundle wraps the mentioned class

**Comment by fd6130** [comment]
> that is basically it ... one important thing is that you have to inject the EntityManagerInterface into your services, not the concrete EntityManager class, because this bundle wraps the mentioned class

What if i use `$this->getDoctrine()->getManager()` instead of injecting the `EntityManagerInterface` in a controller class?

**Comment by Rastusik** [comment]
Then you would bypass the mechanism implemented in this bundle. Doctrine entity manager would be resetted anyway, but in case that you would have somewhere an entity repository in a variable, the repository would be broken... but basically, if you always work wth `getDoctrine()`, you shouldn't even need this bundle
